//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.WorkHistories = new HashSet<WorkHistory>();
        }

        public int CompanyId { get; set; }
        [Display(Name = "Company Name")]
        [Required(ErrorMessage = "Please provide Company Name")]
        [StringLength(50, ErrorMessage = "50 characters only")]
        public string CompanyName { get; set; }
        [Display(Name = "Company Location")]
        [StringLength(50, ErrorMessage = "50 characters only")]
        public string CompanyLoc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkHistory> WorkHistories { get; set; }
    }
}
